#!/usr/bin/env python3
"""Turn art/art.json into src/art_data.rs so the art ships inside the binary."""
import json, re

with open("art/art.json") as f:
    pieces = json.load(f)


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def slug(title, taken):
    s = re.sub(r"[^a-z0-9]+", "-", title.lower()).strip("-") or "art"
    name, n = s, 2
    while name in taken:
        name, n = f"{s}-{n}", n + 1
    taken.add(name)
    return name


taken = set()
rows = []
for p in pieces:
    if not p["title"].strip():
        continue  # untitled scraps, not worth keeping
    art = p["art"].rstrip("\n")
    width = max((len(l) for l in art.split("\n")), default=0)
    height = art.count("\n") + 1
    rows.append((slug(p["title"], taken), p["title"], p["artist"] or "unknown", width, height, art))

with open("src/art_data.rs", "w") as f:
    f.write("//! Generated by tools/gen_art.py from art/art.json — do not edit by hand.\n")
    f.write("//! Art collected from asciiart.eu; artist credit is kept with each piece.\n\n")
    f.write("pub struct Art {\n    pub name: &'static str,\n    pub title: &'static str,\n")
    f.write("    pub artist: &'static str,\n    pub width: usize,\n    pub height: usize,\n")
    f.write("    pub art: &'static str,\n}\n\n")
    f.write(f"pub const ART: [Art; {len(rows)}] = [\n")
    for name, title, artist, width, height, art in rows:
        body = esc(art).replace("\n", "\\n")
        f.write(f'    Art {{ name: "{name}", title: "{esc(title)}", '
                f'artist: "{esc(artist)}", width: {width}, height: {height}, art: "{body}" }},\n')
    f.write("];\n")

print(f"{len(rows)} pieces -> src/art_data.rs")
