//! Picture selection for task slips. The pieces themselves live in art_data.rs,
//! generated by tools/gen_art.py from art/art.json.

pub use crate::art_data::{Art, ART};

/// Pick one at random from the pieces that fit the given width,
/// without pulling in an rng crate.
pub fn random(max_width: usize) -> &'static Art {
    let fitting: Vec<&Art> = ART.iter().filter(|a| a.width <= max_width).collect();
    let nanos = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.subsec_nanos() as usize)
        .unwrap_or(0);
    fitting[nanos % fitting.len()]
}

pub fn by_name(name: &str) -> Option<&'static Art> {
    ART.iter().find(|a| a.name == name)
}

/// Pad every line equally so the picture sits centred as a block.
/// Centring line-by-line with ESC a would shear the drawing apart.
pub fn centred(art: &str, width: usize) -> String {
    let widest = art.lines().map(|l| l.chars().count()).max().unwrap_or(0);
    let pad = " ".repeat(width.saturating_sub(widest) / 2);
    art.lines().map(|l| format!("{pad}{l}")).collect::<Vec<_>>().join("\n")
}
